distro_codename: 17g
distro_title: 17G
distribution: auto
copyright: 17g Developer Team

loop_directory: /dev/loop0
gtk_theme: default

initramfs_system: auto 
using_shell: /bin/bash
use_reboot: false

list_users_when_auto_login: false
autologin_enabled: true
auto_partition_enabled: true
set_root_password: true
use_chpasswd: true

manual_partition_enabled: true 
lvm_enabled: true
encryption_enabled: true
fill_disk_enabled: true
set_alternative_ui: false
welcome_screen: true

default_country_code: auto
default_timezone: America/New_York

skip_language: false
skip_timezone: false
skip_keyboard: false
allow_uppercase_hostname: true
allow_numeric_password: false
min_password_length: 1

additional_user_groups:
  - audio
  - wheel
exclude_dirs:
  - /home
remove_packages:
  - 17g-live-installer
  - archiso 
post_install_commands:
  - echo "Ğ"
  - echo "BRUH"
