distro_codename: 17g
distro_title: 17G
distribution: auto
copyright: 17g Developer Team

loop_directory: /dev/loop0
gtk_theme: Yaru-dark

initramfs_system: mkinitcpio 
using_shell: /bin/bash

list_users_when_auto_login: false
autologin_enabled: true
auto_partition_enabled: true
set_root_password: false

manual_partition_enabled: true 
lvm_enabled: true
encryption_enabled: true
fill_disk_enabled: true

addintional_user_groups:
  - audio
  - wheel
exclude_dirs:
  - /home
remove_packages:
  - 17g-live-installer
  - archiso 
post_install_commands:
  - echo "Ğ"
  - echo "BRUH"
