name: mkinitcpio
check_this_dir: /lib/initcpio
enable_lvm:
  - echo "HOOKS+=(lvm2)" > /etc/mkinitcpio.conf
commands:
  - mkinitcpio -g /boot/initramfs-linux.img
  - mkinitcpio -g /boot/initramfs-linux-fallback.img
