name: inary
check_this_dir: /var/lib/inary
install_package: inary it {packages} -y
remove_package: inary rm {packages} -y
remove_package_with_unusing_deps: inary rm {packages} -y && inary dc
remove_package_with_needed_packages: inary rm {packages} -y
